# Base
FROM alpine:3.7

ENV PG_USER="docker"
ENV PG_HOST="localhost"
ENV PG_DATABASE="gis"
ENV PG_PASSWORD="docker"
ENV PG_PORT="5432"

RUN apk add --no-cache nodejs nodejs-npm tini
VOLUME ["/root/app"]
WORKDIR /root/app
ENTRYPOINT ["/sbin/tini", "--"]

EXPOSE 3000
CMD ["sh", "-c", "npm set progress=false && npm config set depth 0 && npm install && npm run start"]
