language: bash
services:
  - docker
script: docker build -t ${DOCKER_REPO_HOSTNAME}/${DOCKER_REPO_NAME}:$(git rev-parse HEAD) .
deploy:
  - provider: script
    script: "./deploy.sh ${DOCKER_REPO_HOSTNAME} ${DOCKER_REPO_NAME}"
