language: bash

env:
  global:
  - PATH="${HOME}/bin:${PATH}"
  - GEOSERVER_REPO="dtf-street-works-geoserver"
  - MAPS_API_REPO="dtf-street-works-maps-api"
  - MAPS_UI_REPO="dtf-street-works-maps-ui"

services:
  - docker

before_script:
  - echo ${GOOGLE_CREDENTIALS} | base64 --decode > ${HOME}/cicd.json
  - gcloud --quiet version
  - mkdir -p ${HOME}/bin
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x kubectl
  - mv kubectl ${HOME}/bin
  - gcloud config set project $(grep project_id ${HOME}/cicd.json |cut -d\" -f4)
  - gcloud config set compute/zone europe-west2-a
  - gcloud auth activate-service-account $(grep client_email ${HOME}/cicd.json |cut -d\" -f4) --key-file=${HOME}/cicd.json

script:
  - cd geoserver && docker build -t ${DOCKER_REPO_HOSTNAME}/$(grep project_id ${HOME}/cicd.json |cut -d\" -f4)/${GEOSERVER_REPO}:$TRAVIS_COMMIT .
  - ./release.sh ${DOCKER_REPO_HOSTNAME} ${GEOSERVER_REPO} $TRAVIS_COMMIT
  - cd ../
  - cd maps-api && docker build -t ${DOCKER_REPO_HOSTNAME}/$(grep project_id ${HOME}/cicd.json |cut -d\" -f4)/${MAPS_API_REPO}:$TRAVIS_COMMIT .
  - ./release.sh ${DOCKER_REPO_HOSTNAME} ${MAPS_API_REPO} $TRAVIS_COMMIT
  - cd ../
  - cd maps-ui && docker build -t ${DOCKER_REPO_HOSTNAME}/$(grep project_id ${HOME}/cicd.json |cut -d\" -f4)/${MAPS_UI_REPO}:$TRAVIS_COMMIT .
  - ./release.sh ${DOCKER_REPO_HOSTNAME} ${MAPS_UI_REPO} $TRAVIS_COMMIT
  - cd ../

deploy:
  - provider: script
    script: "cd geoserver && ./deploy.sh streetworks-dev-cluster ${DOCKER_REPO_HOSTNAME} ${GEOSERVER_REPO} $TRAVIS_COMMIT && cd ../"
    on:
      branch: master
  - provider: script
    script: "cd maps-api && ./deploy.sh streetworks-dev-cluster ${DOCKER_REPO_HOSTNAME} ${MAPS_API_REPO} $TRAVIS_COMMIT && cd ../"
    on:
      branch: master
  - provider: script
    script: "cd maps-ui && ./deploy.sh streetworks-dev-cluster ${DOCKER_REPO_HOSTNAME} ${MAPS_UI_REPO} $TRAVIS_COMMIT && cd ../"
    on:
      branch: master
