language: bash
services:
  - docker
script: cd proof-of-concepts/example-app-openlayers-persist-postgis && docker build -t ${DOCKER_REPO_HOSTNAME}/${DOCKER_REPO_NAME}:$(git rev-parse HEAD) .
deploy:
  - provider: script
    script: "pwd && ls -l && ./deploy.sh ${DOCKER_REPO_HOSTNAME} ${DOCKER_REPO_NAME}"
    on:
      branch: master
