language: bash

env:
  global:
  - PATH="${HOME}/bin:${PATH}"

services:
  - docker

before_script:
  - echo ${GOOGLE_CREDENTIALS} | base64 --decode > ${HOME}/cicd.json
  - gcloud --quiet version
  - mkdir -p ${HOME}/bin
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x kubectl
  - mv kubectl ${HOME}/bin
  - gcloud config set project $(grep project_id ${HOME}/cicd.json |cut -d\" -f4)
  - gcloud config set compute/zone europe-west2-a
  - gcloud auth activate-service-account $(grep client_email ${HOME}/cicd.json |cut -d\" -f4) --key-file=${HOME}/cicd.json

script:
  - cd proof-of-concepts/example-app-openlayers-persist-postgis && docker build -t ${DOCKER_REPO_HOSTNAME}/$(grep project_id ${HOME}/cicd.json |cut -d\" -f4)/${DOCKER_REPO_NAME}:$TRAVIS_COMMIT .
  - ./release.sh ${DOCKER_REPO_HOSTNAME} ${DOCKER_REPO_NAME} $TRAVIS_COMMIT

deploy:
  - provider: script
    script: "./deploy.sh streetworks-dev-cluster ${DOCKER_REPO_HOSTNAME} ${DOCKER_REPO_NAME} $TRAVIS_COMMIT"
    on:
      branch: master
