language: node_js
node_js:
- lts/*
deploy:
  provider: heroku
  api_key:
    secure: qFG1LJF44QbybTyAUjjyDBIya2HWaE6LlIGBkMXXE9dvXDqHBOSUFLjd/w7LFICSWg+WkBvccwIm+XvARLvXjeTH3CaNnzJ9QD1LQWLgfLngsCD5KK0lnXAe65S6VyrTew7tZ15Mts8fR0n1wVJujNrmVRqlVWRbhL28ITwpwfu7MIaSDmk9u6PfjvceJf3SWg+LNuB1YrhEiKrU7BHXXLIxl+5yzvPX1g4NJx7sNVqq1TF1f6AmDRsW5Oeo2MWVvHNVM48H5knmz9fsEkmnTN493jEcaFlJsS+1xrRPwdJ2IwdKdxhqpazJ0mdRNZQRYde2O+OIyiAyVnVQQn2dkhhK5Bdbg37woD+db3ZlXAe4LEHJ6aHx88XbzM5SSDmsgc1WAG88tBK0Bj3w80ULXydnvw8oN2Dbjt3dfozmg6V4M/199u9ZbFsg+5NZzkAwn1eI6+GdBfZDrLcb3kF3uTlAfZH0V/CH3amX1UW1xaLXaz3/t95ZngIXyjbWyQDV2Xk7ot4LeRlMqIDnOvCchEc7DvQyTrv+YlWNTKrugrx6FHayL5C4Q4gQDvIwwc/oomaiPd6//DrdVxUp8GKCKm/h6pqjQ/9pasdPMWKmK8At+28Ne0SMu2rJmm+RB9J8XGEmsZUOy7RISoOUmLZPY6xYxGGut6Torwync6hPnsU=
  app: dft-street-manager-ux
