# Base
FROM alpine:3.7
RUN apk add --no-cache nodejs nodejs-npm tini
VOLUME ["/root/app"]
WORKDIR /root/app
ENTRYPOINT ["/sbin/tini", "--"]

EXPOSE 3000
CMD ["sh", "-c", "npm set progress=false && npm config set depth 0 && npm install && npm run start"]
