module.exports = [
  {
    // Plan & Create
    promoterName: 'JOHN CARRINGTON',
    USRN: '08400189',
    roadCategoryGroup: '1',
    highwayAuthority: 'Highway Authority',
    workReferenceNumber: 'CT0224443466',
    startDay: '28',
    startMonth: '03',
    startYear: '2017',
    endDay: '30',
    endMonth: '03',
    endYear: '2017',
    duration: '2 Days',
    trafficManagementTypeGroup: 'Stop/go boards',
    workCategoryGroup: 'Minor',
    screen1Complete: true,
    // Location & contact
    worksLocationDescription: 'Location 1234',
    worksLocationGroup: [ 'Footway', 'Cycleway' ],
    descriptionOfWorkGroup: 'Leakage',
    descriptionOfWork2: '',
    excavationGroup: 'Yes',
    contactDetails: 'Brian Smith - 077389477298',
    promoterAgent: '',
    secondaryContact: '',
    commerciallySensitiveGroup: 'No',
    laneRentalGroup: 'No',
    screen2Complete: true,
    // Conditions
    conditionsName: ['NCT01a'],
    conditionsReason: ['Standard Condition'],
    screen3Complete: true,
    // Collaboration
    tmGroup: 'Yes',
    fileAttachedDetail: ['TM Plan'],
    fileAttachedName: ['c17-2006.png'],
    collaborationGroup: 'No',
    collaborationTypeGroup: '',
    collaborationDetails: '',
    environmentalHealthGroup: 'No',
    projectReference: 'ABC12345',
    screen4Complete: true,
    // Assess
    screen5Complete: true,
    // On Site
    actualStartDateDay: '21',
    actualStartDateMonth: '02',
    actualStartDateYear: '2018',
    actualStartDateHour: '08',
    actualStartDateMinute: '00',
    actualEndDateDay: '23',
    actualEndDateMonth: '02',
    actualEndDateYear: '2018',
    actualEndDateHour: '15',
    actualEndDateMinute: '00',
    excavationRequiredGroup: 'Yes',
    screen6Complete: true
  },

  {
    // Plan & Create
    promoterName: 'BOB SMITH',
    USRN: '084001234',
    roadCategoryGroup: '3',
    highwayAuthority: 'Highway authority 1234',
    workReferenceNumber: 'CT0938475839',
    startDay: '01',
    startMonth: '05',
    startYear: '2018',
    endDay: '03',
    endMonth: '05',
    endYear: '2018',
    duration: '3 days',
    trafficManagementTypeGroup: 'Road closure',
    workCategoryGroup: 'Major',
    screen1Complete: true,
    // Location & contact
    worksLocationDescription: 'Location 3456',
    worksLocationGroup: [ 'Footway' ],
    descriptionOfWorkGroup: 'New supply',
    descriptionOfWork2: 'Leakage',
    excavationGroup: 'Yes',
    contactDetails: 'Andy Jones - 07728394829',
    promoterAgent: '',
    secondaryContact: '',
    commerciallySensitiveGroup: 'Yes',
    laneRentalGroup: 'No',
    screen2Complete: true,
    // Conditions
    conditionsName: ['NCT06a'],
    conditionsReason: ['Standard Condition'],
    screen3Complete: true,
    // Collaboration
    tmGroup: '',
    fileAttachedDetail: ['New TM plan'],
    fileAttachedName: ['b34-2018.png'],
    collaborationGroup: 'No',
    collaborationTypeGroup: '',
    collaborationDetails: '',
    environmentalHealthGroup: 'No',
    projectReference: 'FGH2358125',
    screen4Complete: true,
    // Assess
    screen5Complete: true,
    // On Site
    actualStartDateDay: '01',
    actualStartDateMonth: '05',
    actualStartDateYear: '2018',
    actualStartDateHour: '09',
    actualStartDateMinute: '00',
    actualEndDateDay: '03',
    actualEndDateMonth: '05',
    actualEndDateYear: '2018',
    actualEndDateHour: '17',
    actualEndDateMinute: '00',
    excavationRequiredGroup: 'Yes',
    screen6Complete: true
  },

  {
    // Plan & Create
    promoterName: '',
    USRN: '',
    roadCategoryGroup: '',
    highwayAuthority: '',
    workReferenceNumber: '',
    startDay: '',
    startMonth: '',
    startYear: '',
    endDay: '',
    endMonth: '',
    endYear: '',
    duration: '',
    trafficManagementTypeGroup: '',
    workCategoryGroup: '',
    screen1Complete: false,
    // Location & contact
    worksLocationDescription: '',
    worksLocationGroup: [ '' ],
    descriptionOfWorkGroup: '',
    descriptionOfWork2: '',
    excavationGroup: '',
    contactDetails: '',
    promoterAgent: '',
    secondaryContact: '',
    commerciallySensitiveGroup: '',
    laneRentalGroup: '',
    screen2Complete: false,
    // Conditions
    conditionsName: [''],
    conditionsReason: [''],
    screen3Complete: false,
    // Collaboration
    tmGroup: '',
    fileAttachedDetail: [''],
    fileAttachedName: [''],
    collaborationGroup: '',
    collaborationTypeGroup: '',
    collaborationDetails: '',
    environmentalHealthGroup: '',
    projectReference: '',
    screen4Complete: false,
    // Assess
    screen5Complete: false,
    // On Site
    actualStartDateDay: '',
    actualStartDateMonth: '',
    actualStartDateYear: '',
    actualStartDateHour: '',
    actualStartDateMinute: '',
    actualEndDateDay: '',
    actualEndDateMonth: '',
    actualEndDateYear: '',
    actualEndDateHour: '',
    actualEndDateMinute: '',
    excavationRequiredGroup: 'Yes',
    screen6Complete: true
  }
]
