apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dft-street-manager-geoserver-deployment
spec:
  selector:
    matchLabels:
      app: dft-street-manager-geoserver
  replicas: 2
  template:
    metadata:
      labels:
        app: dft-street-manager-geoserver
    spec:
      containers:
      - name: dft-street-manager-geoserver
        image: <DOCKER_REPO_HOSTNAME>/<DOCKER_PROJECT_ID>/<DOCKER_REPO_NAME>:<DOCKER_TAG>
        env:
          - name: MASTERPASSWORD
            valueFrom:
              secretKeyRef:
                name: geoserver-config
                key: MASTERPASSWORD
          - name: CONFIG_BUCKET
            valueFrom:
              configMapKeyRef:
                name: geoserver-config
                key: bucket
          - name: CONFIG_VERSION
            valueFrom:
              configMapKeyRef:
                name: geoserver-config
                key: version
          - name: PG_USER
            valueFrom:
              secretKeyRef:
                name: database
                key: PG_USER
          - name: PG_HOST
            valueFrom:
              secretKeyRef:
                name: database
                key: PG_HOST
          - name: PG_DATABASE
            valueFrom:
              secretKeyRef:
                name: database
                key: PG_DATABASE
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database
                key: PG_PASSWORD
          - name: PG_PORT
            valueFrom:
              secretKeyRef:
                name: database
                key: PG_PORT
          - name: GOOGLE_KEY_FILE
            valueFrom:
              secretKeyRef:
                name: geoserver-config
                key: SERVICE_ACCOUNT_FILE
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: 2048Mi
            cpu: 1
          requests:
            memory: 1024Mi
            cpu: 0.5
      nodeSelector:
        system: "false"
