apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dft-street-manager-geoserver-deployment
spec:
  selector:
    matchLabels:
      app: dft-street-manager-geoserver
  replicas: 2
  template:
    metadata:
      labels:
        app: dft-street-manager-geoserver
    spec:
      containers:
      - name: dft-street-manager-geoserver
        image: <DOCKER_REPO_HOSTNAME>/<DOCKER_PROJECT_ID>/<DOCKER_REPO_NAME>:<DOCKER_TAG>
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: 2048Mi
            cpu: 1m
          requests:
            memory: 1024Mi
            cpu: 500m
      nodeSelector:
        system: false
