apiVersion: v1
kind: Service
metadata:
  labels:
    app: dft-street-manager-api
  name: dft-street-manager-api-service
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: dft-street-manager-api
