version: "3.2"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/opt/app
    environment:
      - PG_HOST=db

  db:
    image: kartoza/postgis:9.6-2.4

  db_provision:
    build: ./docker/db_provision
    environment:
      - PG_HOST=db
    depends_on:
      - db
